python: can't open file '/root/TCPUDP/udps/main.py': [Errno 2] No such file or directory
python: can't open file '/root/TCPUDP/udps/main.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/root/TCPUDP/udps/main.py", line 21, in <module>
    server.bind((bind_ip, bind_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/root/TCPUDP/udps/main.py", line 21, in <module>
    server.bind((bind_ip, bind_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
